// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: hagw.proto

package hagw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HAState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State      string                `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Attributes map[string]*anypb.Any `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metadata   map[string]string     `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HAState) Reset() {
	*x = HAState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HAState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HAState) ProtoMessage() {}

func (x *HAState) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HAState.ProtoReflect.Descriptor instead.
func (*HAState) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{0}
}

func (x *HAState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HAState) GetAttributes() map[string]*anypb.Any {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *HAState) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *StateReq) Reset() {
	*x = StateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReq) ProtoMessage() {}

func (x *StateReq) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReq.ProtoReflect.Descriptor instead.
func (*StateReq) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{1}
}

func (x *StateReq) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

type StateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *HAState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *StateResp) Reset() {
	*x = StateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResp) ProtoMessage() {}

func (x *StateResp) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResp.ProtoReflect.Descriptor instead.
func (*StateResp) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{2}
}

func (x *StateResp) GetState() *HAState {
	if x != nil {
		return x.State
	}
	return nil
}

type SubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *SubscribeReq) Reset() {
	*x = SubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReq) ProtoMessage() {}

func (x *SubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReq.ProtoReflect.Descriptor instead.
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeReq) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

type SubscribeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeResp) Reset() {
	*x = SubscribeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResp) ProtoMessage() {}

func (x *SubscribeResp) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResp.ProtoReflect.Descriptor instead.
func (*SubscribeResp) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{4}
}

type CallServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity  string                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Domain  string                `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Service string                `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Data    map[string]*anypb.Any `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CallServiceReq) Reset() {
	*x = CallServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServiceReq) ProtoMessage() {}

func (x *CallServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServiceReq.ProtoReflect.Descriptor instead.
func (*CallServiceReq) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{5}
}

func (x *CallServiceReq) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *CallServiceReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CallServiceReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CallServiceReq) GetData() map[string]*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type CallServiceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CallServiceResp) Reset() {
	*x = CallServiceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServiceResp) ProtoMessage() {}

func (x *CallServiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServiceResp.ProtoReflect.Descriptor instead.
func (*CallServiceResp) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{6}
}

type FireEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType string                `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Event     map[string]*anypb.Any `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FireEventReq) Reset() {
	*x = FireEventReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FireEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireEventReq) ProtoMessage() {}

func (x *FireEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireEventReq.ProtoReflect.Descriptor instead.
func (*FireEventReq) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{7}
}

func (x *FireEventReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *FireEventReq) GetEvent() map[string]*anypb.Any {
	if x != nil {
		return x.Event
	}
	return nil
}

type FireEventResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FireEventResp) Reset() {
	*x = FireEventResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hagw_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FireEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireEventResp) ProtoMessage() {}

func (x *FireEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_hagw_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireEventResp.ProtoReflect.Descriptor instead.
func (*FireEventResp) Descriptor() ([]byte, []int) {
	return file_hagw_proto_rawDescGZIP(), []int{8}
}

var File_hagw_proto protoreflect.FileDescriptor

var file_hagw_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x61,
	0x67, 0x77, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x02,
	0x0a, 0x07, 0x48, 0x41, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x3d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x48, 0x41, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x37,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x48, 0x41, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x53, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3b, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x22, 0x0a, 0x08, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x30, 0x0a,
	0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68, 0x61, 0x67, 0x77,
	0x2e, 0x48, 0x41, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x26, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0xdd, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4d, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0xb1, 0x01, 0x0a, 0x0c,
	0x46, 0x69, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x61, 0x67, 0x77,
	0x2e, 0x46, 0x69, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a,
	0x4e, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x0f, 0x0a, 0x0d, 0x46, 0x69, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x32, 0xd4, 0x01, 0x0a, 0x04, 0x48, 0x61, 0x67, 0x77, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0e, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x12, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x48, 0x41, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x68, 0x61, 0x67,
	0x77, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x34, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x46, 0x69, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x68, 0x61, 0x67, 0x77, 0x2e, 0x46, 0x69, 0x72, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x68, 0x61, 0x67,
	0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hagw_proto_rawDescOnce sync.Once
	file_hagw_proto_rawDescData = file_hagw_proto_rawDesc
)

func file_hagw_proto_rawDescGZIP() []byte {
	file_hagw_proto_rawDescOnce.Do(func() {
		file_hagw_proto_rawDescData = protoimpl.X.CompressGZIP(file_hagw_proto_rawDescData)
	})
	return file_hagw_proto_rawDescData
}

var file_hagw_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_hagw_proto_goTypes = []interface{}{
	(*HAState)(nil),         // 0: hagw.HAState
	(*StateReq)(nil),        // 1: hagw.StateReq
	(*StateResp)(nil),       // 2: hagw.StateResp
	(*SubscribeReq)(nil),    // 3: hagw.SubscribeReq
	(*SubscribeResp)(nil),   // 4: hagw.SubscribeResp
	(*CallServiceReq)(nil),  // 5: hagw.CallServiceReq
	(*CallServiceResp)(nil), // 6: hagw.CallServiceResp
	(*FireEventReq)(nil),    // 7: hagw.FireEventReq
	(*FireEventResp)(nil),   // 8: hagw.FireEventResp
	nil,                     // 9: hagw.HAState.AttributesEntry
	nil,                     // 10: hagw.HAState.MetadataEntry
	nil,                     // 11: hagw.CallServiceReq.DataEntry
	nil,                     // 12: hagw.FireEventReq.EventEntry
	(*anypb.Any)(nil),       // 13: google.protobuf.Any
}
var file_hagw_proto_depIdxs = []int32{
	9,  // 0: hagw.HAState.attributes:type_name -> hagw.HAState.AttributesEntry
	10, // 1: hagw.HAState.metadata:type_name -> hagw.HAState.MetadataEntry
	0,  // 2: hagw.StateResp.state:type_name -> hagw.HAState
	11, // 3: hagw.CallServiceReq.data:type_name -> hagw.CallServiceReq.DataEntry
	12, // 4: hagw.FireEventReq.event:type_name -> hagw.FireEventReq.EventEntry
	13, // 5: hagw.HAState.AttributesEntry.value:type_name -> google.protobuf.Any
	13, // 6: hagw.CallServiceReq.DataEntry.value:type_name -> google.protobuf.Any
	13, // 7: hagw.FireEventReq.EventEntry.value:type_name -> google.protobuf.Any
	1,  // 8: hagw.Hagw.state:input_type -> hagw.StateReq
	3,  // 9: hagw.Hagw.subscribe:input_type -> hagw.SubscribeReq
	5,  // 10: hagw.Hagw.callService:input_type -> hagw.CallServiceReq
	7,  // 11: hagw.Hagw.fireEvent:input_type -> hagw.FireEventReq
	2,  // 12: hagw.Hagw.state:output_type -> hagw.StateResp
	0,  // 13: hagw.Hagw.subscribe:output_type -> hagw.HAState
	6,  // 14: hagw.Hagw.callService:output_type -> hagw.CallServiceResp
	8,  // 15: hagw.Hagw.fireEvent:output_type -> hagw.FireEventResp
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_hagw_proto_init() }
func file_hagw_proto_init() {
	if File_hagw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hagw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HAState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServiceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FireEventReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hagw_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FireEventResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hagw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hagw_proto_goTypes,
		DependencyIndexes: file_hagw_proto_depIdxs,
		MessageInfos:      file_hagw_proto_msgTypes,
	}.Build()
	File_hagw_proto = out.File
	file_hagw_proto_rawDesc = nil
	file_hagw_proto_goTypes = nil
	file_hagw_proto_depIdxs = nil
}
